app:
  version: "0.0.1"
  desc: "The api server"
# Postgres
pdb:
  addr: "postgres://admin:admin123@127.0.0.1:32599/cdb"
# Redis database
rdb:
  addr: "127.0.0.1:30000"
log:
  path: "./logs"
api_server:
  bind: "127.0.0.1:8080"
